# pubspec.yaml
name: t0703
description: "A new Flutter project."
publish_to: 'none' # pub.dev에 게시하지 않을 경우 이 줄을 유지합니다.

version: 1.0.0+1

environment:
  sdk: '>=3.8.1 <4.0.0' # Flutter SDK 버전을 3.8.1 이상으로 설정

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8 # iOS 스타일 아이콘 최신 버전
  go_router: ^13.0.1 # 라우팅을 위한 GoRouter 패키지
  provider: ^6.1.2 # 상태 관리를 위한 Provider 패키지
  http: ^1.2.1 # HTTP 통신을 위한 패키지 (최신 안정 버전)
  table_calendar: ^3.0.9 # 캘린더 위젯을 위한 패키지 (의료진 캘린더에 필요)

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1 # Flutter 코드 린트 규칙 최신 버전

flutter:
  uses-material-design: true
